spring.application.name=chat

#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=581993@Attack
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=selfsigned
#server.port=8443

# allow React app on these origins to call REST endpoints
spring.mvc.cors.mapping=/api/**
spring.mvc.cors.allowed-origins=http://localhost:3000,http://192.168.1.8:3000
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allow-credentials=true


server.address=0.0.0.0
server.port=8080
